# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

spreadsheetIds: ['REPLACE_SPREADSHEET_IDS'] # Replace with an array of spreadsheet IDs. e.g.['ID1', 'ID2']
#driveFolderIds: ['REPLACE_DRIVE_FOLDER_IDS'] # Replace with google drive folder id if you want to specify drive directory
youtubeServiceEnable: False # Enable YouTube Service by chaning the config to True.
#youtubeWindow: 6 # Number of months backdated from today, for which the tool will retrieve video URLs from the YT channel default 6 (months).
refreshMappingSheetEnable: False # Enable refresing mapping sheet if you want the tool to automatically update mapping sheets up-to-date


# DO NOT EDIT BELOW
adsAccount: config/google-ads.yaml # Replace with the path to ad account yaml file (google-ads.yaml) if you plan to save it somewhere else.
serviceAccount: PATH_TO_SERVICE_JSON # DO NOT EDIT
clientSecret: PATH_TO_CLIENT_SECRET_JSON # DO NOT EDIT
